[package]
name = "mana2"
version = "0.1.0"
edition = "2021"
rust-version = "1.74"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "mana"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.4.18", features = ["derive", "wrap_help"] }
git2 = { version = "0.18.1", features = ["vendored-libgit2"], default-features = false }
mlua = { version = "0.9.4", features = ["lua54", "vendored"] }
path-slash = "0.2.1"
peg = "0.8.2"
tempfile = "3.9.0"
thiserror = "1.0.56"
toml = { version = "0.8.8", features = ["preserve_order"] }
unicase = "2.7.0"

