[package]
name = "f-lua"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
effectors = { path = "..", version = "0.2.0", package = "care-effectors" }
fn-error-context = "0.2.1"
mlua = { version = "0.9.4", features = ["lua54", "vendored"] }
path-slash = "0.2.1"
