[package]
name = "f-zeroinstall"
version = "0.1.0"
edition = "2021"

[dependencies]
effectors = { path = "..", version = "0.2.0", package = "care-effectors" }
anyhow = { workspace = true }
itertools = "0.12.1"
log = { workspace = true }
path-slash = { workspace = true }
tempfile = { workspace = true }
url = { workspace = true }
yaserde = { workspace = true, features = ["yaserde_derive"] }
xml-rs = { workspace = true }
