[package]
name = "script"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
log = "0.4.22"
parse_ncl = { path = "parse_ncl" }
toml = { version = "0.8.8", features = ["preserve_order"] }
