[package]
name = "parse_ncl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
nickel-lang-core = { workspace = true }
toml = { workspace = true, features = ["preserve_order"] }
whoami = { workspace = true }

