name: cargo build & test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
      with:
        key: "${{ github.ref }}"   # experiment to maybe avoid pollution btw. branches
    - name: Build
      run: cargo build  # --verbose  ## verbose disabled, as it's too loud normally
    - name: Run tests
      run: cargo test --workspace  # --verbose
